### PR TITLE
Issue #108 Fade out unnecessary boolean literals, and fixing quality flaw

### LINKED ISSUE #108: Fade out unnecessary boolean literals

### PR DESCRIPTION
**Pull request by tvsonar**
Fixes #108

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
The error location should include the binary operator:

{code}
SomeBooleanFunction() == true;
                                        ~~~~~~ this whole part is unused
{code}

The same logic goes for `!=`, `&&`, `||` and `!`

File: src/SonarLint/Rules/BooleanLiteralUnnecessary.cs [hunk 1]
```diff
@@ -40,36 +41,98 @@ public class BooleanLiteralUnnecessary : DiagnosticAnalyzer
...
+                        c.ReportDiagnostic(Diagnostic.Create(Rule, logicalNot.Operand.GetLocation(), logicalNot.Operand.ToString()));
+                        return;
                     }
                 },
-                SyntaxKind.TrueLiteralExpression,
-                SyntaxKind.FalseLiteralExpression);
+                SyntaxKind.LogicalNotExpression);
+        }
+
+        private static void ReportIssue(BinaryExpressionSyntax binaryExpression, bool leftSide, ExpressionSyntax expressionToCheck,
```
Comment (dbolkensteyn) [inline src/SonarLint/Rules/BooleanLiteralUnnecessary.cs]: @tvsonar this method doesn't do what it saids - it doesn't simply report an issue: It should likely more be called "CheckSomething" - or the `SyntaxFactory.AreEquivalent()` moved out

File: src/SonarLint/Rules/BooleanLiteralUnnecessary.cs [hunk 2]
```diff
@@ -40,36 +41,98 @@ public class BooleanLiteralUnnecessary : DiagnosticAnalyzer
...
+                },
+                SyntaxKind.EqualsExpression,
+                SyntaxKind.LogicalAndExpression);
+
+            context.RegisterSyntaxNodeAction(
+                c =>
+                {
+                    var binaryExpression = (BinaryExpressionSyntax)c.Node;
+
+                    ReportIssue(binaryExpression, true, FalseExpression, true, c);
```
Comment (dbolkensteyn) [inline src/SonarLint/Rules/BooleanLiteralUnnecessary.cs]: @tvsonar it is quite a bad idea to pass boolean values to methods: looking back at the code, it is not clear what this boolean flag does.

A better way is to add one new properly-named method for the `true` case, another one for the `false` one, which then both simply call the real method with the right flag

**Comment by dbolkensteyn** [comment]
LGTM
