### PR TITLE
Issue #173 Fade out and add code fix to catch blocks with only a throw in them (S2737)

### LINKED ISSUE #173: Fade out and add code fix to catch blocks with only a throw in them (S2737)
```
try
{
 doSomething();
}
catch(Exception)
{
  throw;
}
```
is equivalent to 
```
doSomething();
```

### PR DESCRIPTION
**Pull request by tvsonar**
Fixes #173

### CODE REVIEW

File: src/SonarLint/Rules/CatchRethrowCodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+                return;
+            }
+
+            if (tryStatement.Catches.Count > 1 ||
+                tryStatement.Finally != null)
+            {
+                context.RegisterCodeFix(
+                    CodeAction.Create(
+                        Title,
+                        c => RedundantParenthesesCodeFixProvider.RemoveUnusedCode(context.Document, syntaxNode,
```
Comment (dbolkensteyn) [inline src/SonarLint/Rules/CatchRethrowCodeFixProvider.cs]: @tvsonar let's not use the `RedundantParenthesesCodeFixProvider` as discussed

**Comment by dbolkensteyn** [comment]
LGTM
